name: CI

on: push

jobs:
  fe-checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install modules
        run: yarn
        working-directory: .
      - name: Run ESLint
        run: yarn run lint:report
        working-directory: .
      - name: Upload ESLint report
        uses: actions/upload-artifact@v3
        with:
          name: eslint-report
          path: ./eslint-report.json
      - name: Run Stylelint
        run: yarn run stylelint:report
        working-directory: .
      - name: Upload Stylelint report
        uses: actions/upload-artifact@v3
        with:
          name: stylelint-report
          path: ./stylelint-report.json
      - name: Run Prettier
        run: yarn run format
        working-directory: .


  fe-test:
    needs: [fe-checkstyle]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn
        working-directory: .
      - run: yarn test:report --ci
        working-directory: .
      - name: Upload Jest report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./test-report.xml
      - name: Upload Jest lcov
        uses: actions/upload-artifact@v3
        with:
          name: lcov-report
          path: ./coverage/lcov.info

  fe-build:
    runs-on: ubuntu-latest
    needs: [fe-test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: yarn
        working-directory: .
      - run: yarn build
        working-directory: .

  fe-report:
    needs: [fe-checkstyle, fe-test]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/development' }} # only creates a report on the development branch
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download Eslint report
        uses: actions/download-artifact@v3
        with:
          name: eslint-report
          path: .
      - name: Download Stylelint report
        uses: actions/download-artifact@v3
        with:
          name: stylelint-report
          path: .
      - name: Download Jest report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: .
      - name: Download Jest lcov
        uses: actions/download-artifact@v3
        with:
          name: lcov-report
          path: ./coverage
      - run: yarn
        working-directory: .
      - run: yarn sonar
        working-directory: .